version: '3'

services:
  in.api:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'DatabasePath=C:\db\{0}.db'
    volumes:
      - C:\db:C:\db
    ports:
      - "5000:80"
  out.api:
    env_file: 
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'DatabasePath=C:\db\{0}.db'
    volumes:
      - C:\db:C:\db
    ports:
      - "59199:80"
networks:
  default:
    external:
      name: nat