version: '3'

services:
  in.api:
    image: neurul/cortex.in.api:0.2.1
    build:
      context: .
      dockerfile: main\Port.Adapter\In\Api\Dockerfile


  out.api:
    image: neurul/cortex.out.api:0.2.1
    build:
      context: .
      dockerfile: main\Port.Adapter\Out\Api\Dockerfile

